# Generated by Django 5.1 on 2024-08-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='make_available',
            new_name='anwser_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_of_answer_required',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type_of_reponse_required',
            field=models.CharField(choices=[('Text', 'Text'), ('Selection', 'Selection'), ('File', 'File')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.FileField(upload_to='FileResponses')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_responses', to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='ImageReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ImageField(upload_to='ImageResponses')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_responses', to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_responses', to='main.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.options')),
            ],
        ),
    ]
