# Generated by Django 5.1 on 2024-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
