# Generated by Django 5.1 on 2024-08-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_make_available_question_anwser_required_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileReponse',
            new_name='FileResponse',
        ),
        migrations.RenameModel(
            old_name='ImageReponse',
            new_name='ImageResponse',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_of_reponse_required',
        ),
        migrations.AddField(
            model_name='question',
            name='type_of_response_required',
            field=models.CharField(choices=[('Text', 'Text'), ('Selection', 'Selection'), ('File', 'File'), ('Image', 'Image')], default='Text', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_responses', to='main.question')),
            ],
        ),
    ]
