# Generated by Django 5.1 on 2024-08-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_filereponse_fileresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='anwser_required',
            new_name='answer_required',
        ),
    ]
