# Generated by Django 5.1 on 2024-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fileresponse_created_at_imageresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
