name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }} 
  POSTGRES_USER_PASSWORD: ${{ secrets.POSTGRES_USER_PASSWORD }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }} 
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
